### ISSUE TITLE
QQvip签到：今日发现自动签到或手动签到无限提示“天啦噜，活动实在太火爆了，请待会再来瞅瞅呗！”

### ISSUE THREAD

**Issue by Nyim1s** [lowking/Scripts#1]
如题。
quanx：1.0.11
iOS：13.5.1

**Comment by Nyim1s** [comment]
更新：彻底删掉QQ，重新下载之后，就好了。
（从头到尾非TF版）

**Comment by lowking** [comment]
> 更新：彻底删掉QQ，重新下载之后，就好了。
> （从头到尾非TF版）

这提示是腾讯那边返回的，要么是cookie过期了，要么是服务器问题
所以建议按如下设置，一直开着获取cookie
![image](https://user-images.githubusercontent.com/33308659/85843136-54fbec00-b7d3-11ea-9cd3-15389099710f.png)

**Comment by Nyim1s** [comment]
谢谢
