### ISSUE TITLE
qq会员签到cookie

### ISSUE THREAD

**Issue by Tianlengle** [lowking/Scripts#12]
## 问题脚本
qq会员签到获取cookie  

## 问题描述
我按脚本上的提示的滑动获取不到cookie  但是可以用以下路径获取cookie  此处折腾了老半天！
进去之后-成长-成长储值奖励-立即恢复成长值-获取cookie成功    
## 日志描述

https://user-images.githubusercontent.com/45476254/103146059-d7636980-477e-11eb-8461-17d0c599199b.mp4

```
小白 不会看日志 望谅解！！！！
```

**Comment by lowking** [comment]
感谢反馈，已调整脚本注释

**Comment by Tianlengle** [comment]
应该的 大佬 ！ 希望你一直更新下去 赞！！！

lowking <notifications@github.com> 于2020年12月28日周一 下午12:12写道：
