### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by scramjetFoam** [lowking/Scripts#13]
## 问题描述
请问，我填写了telegram通知地址，网页测试也正常，但是脚本运行，提示 请填写tg通知url❌

https://api.telegram.org/bot1957xxxx:xxxxxxxx-_Dlxu1agso0hYjrieivSxf4/sendMessage?chat_id=-55xxxxx&parse_mode=Markdown&text=

## 日志描述
```
{"result":"","output":""}
```

**Comment by WindStill** [comment]
我是github监控报这个错误。看了下，代码里获取的变量名跟配置里的不一样。代码里是 lkGithubMonitorTgNotifyUrl，配置里是 lkTgNotifyUrlGithubMonitorPushTg。所以每次执行都报你这个错误

作者改一下啊。

**Comment by lowking** [comment]
之前本来想用ToolKit重构监控的，后来没写完，竟然把boxjs的订阅配置提交了
现在回滚了配置😂
