### ISSUE TITLE
[BUG]Loon使用索尼签到脚本失败

### ISSUE THREAD

**Issue by xaver985** [lowking/Scripts#14]
## 问题脚本
sonyClub.js

## 问题描述
Loon使用脚本不会自动登录

## 日志描述
```

索尼俱乐部签到, 开始执行!

██{"url":"https://www.sonystyle.com.cn/eSolverOmniChannel/account/signupPoints.do?channel=WAP&access_token=","headers":{"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15"}}

██<?xml version='1.0' encoding='UTF-8'?><com.sonystyle.webservices.dto.common.SonyStyleEmptyDataResponse>
  <resultMsg>
    <com.sonystyle.webservices.v2.util.SonyStyleResponseMessage>
      <code>98</code>
      <message>登陆状态已失效，请重新登录</message>
    </com.sonystyle.webservices.v2.util.SonyStyleResponseMessage>
  </resultMsg>
  <resultData/>
</com.sonystyle.webservices.dto.common.SonyStyleEmptyDataResponse>

██索尼俱乐部签到执行完毕！耗时【1.437】秒
总共执行【28】次，平均耗时【2.7101】秒

```
经过与Loon作者沟通，Loon作者说代码与Loon不兼容
![7B938B12-8E2F-4CDF-851A-BEB98D7F7897](https://user-images.githubusercontent.com/32983060/133280917-8b1076aa-5f05-4c42-9504-ef4952711816.jpeg)

“这边的代码写的和loon不兼容，data不是undefined“

**Comment by lowking** [comment]
本人没有loon，loon的http请求结果和surge不一样？这么奇葩的吗。我看了surge的日志是undefined。我尝试兼容下

**Comment by xaver985** [comment]
感谢作者，现在是可以自动登录了，但还不会签到😥

**Comment by xaver985** [comment]
索尼俱乐部签到, 开始执行!

██{"url":"https://www.sonystyle.com.cn/eSolverOmniChannel/account/signupPoints.do?channel=WAP&access_token=","headers":{"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15"}}

██<?xml version='1.0' encoding='UTF-8'?><com.sonystyle.webservices.dto.common.SonyStyleEmptyDataResponse>
  <resultMsg>
    <com.sonystyle.webservices.v2.util.SonyStyleResponseMessage>
      <code>98</code>
      <message>登陆状态已失效，请重新登录</message>
    </com.sonystyle.webservices.v2.util.SonyStyleResponseMessage>
  </resultMsg>
  <resultData/>
</com.sonystyle.webservices.dto.common.SonyStyleEmptyDataResponse>

██进入自动登录

██第1次尝试登录

██{"url":"https://www.sonystyle.com.cn/eSolverOmniChannel/account/login.do","headers":{"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15","Content-Type":"application/json"},"body":"{\"channel\":\"WAP\",\"loginID\":\"\",\"password\":\"\"}"}

██<?xml version='1.0' encoding='UTF-8'?><sonyStyleLoginResult><resultData><access_token>84aad506-48ee-490d-8275-1c3a41fe3f7d</access_token><customerGroup>bronzecustomergroup</customerGroup><customerID>0011875014</customerID><realName></realName><userAlias></userAlias></resultData><resultMsg><code>00</code><message>成功</message></resultMsg></sonyStyleLoginResult>

██索尼俱乐部签到执行完毕！耗时【0.911】秒
总共执行【30】次，平均耗时【2.6142】秒

**Comment by lowking** [comment]
尝试了下，在代理软件内部缺少环境，将xml格式的返回数据转换成json，处理起来比较麻烦
不知道为什么loon会返回xml，还是得等用loon的会js的来处理，或者让loon作者修复这个问题

**Comment by Zephyr-Ran** [comment]
大佬，想问个特别弱智的问题，就是我QX配置好了您的sony签到脚本，也配置好了BOXJS，但是在运营QX脚本的时候就提示要到BoxJs里面添加账号密码，但是进到boxjs里面什么也没有，boxjs添加您的脚本订阅就显示格式错误。可能问题比较弱智，盼复。

**Comment by lowking** [comment]
> 大佬，想问个特别弱智的问题，就是我QX配置好了您的sony签到脚本，也配置好了BOXJS，但是在运营QX脚本的时候就提示要到BoxJs里面添加账号密码，但是进到boxjs里面什么也没有，boxjs添加您的脚本订阅就显示格式错误。可能问题比较弱智，盼复。

你订阅地址对了吗？
https://raw.githubusercontent.com/lowking/Scripts/master/lowking.boxjs.json
