### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chengkongyiban** [lowking/Scripts#16]
## 问题脚本
hifini签到脚本

## 问题描述
loon使用hifini签到脚本失败，使用小火箭签到没问题。

## 日志描述
```
这里填写问题脚本输出的日志，否则无法定位问题
```██hifini签到, 开始执行!

██开始签到

██hifini签到执行异常:
TypeError: undefined is not an object (evaluating 'data.split(`<h4 class="card-title text-center mb-0">`)[1].split')

undefined is not an object (evaluating 'data.split(`<h4 class="card-title text-center mb-0">`)[1].split')

██返回数据：{}

██hifini签到执行完毕！耗时【1.249】秒
总共执行【13】次，平均耗时【0.7513】秒

**Comment by lowking** [comment]
没有loon，尝试修复了下，你再看看

**Comment by chengkongyiban** [comment]
刚刚试了，签到异常

██hifini签到执行异常:
TypeError: undefined is not an object (evaluating 'data.split(`<h4 class="card-title text-center mb-0">`)[1].split')

undefined is not an object (evaluating 'data.split(`<h4 class="card-title text-center mb-0">`)[1].split')

**Comment by lowking** [comment]
那就不知道了，等哪天有loon了再调试了😂

**Comment by chengkongyiban** [comment]
> 那就不知道了，等哪天有loon了再调试了😂

谢谢大佬的脚本，先在小火箭用着先

**Comment by chengkongyiban** [comment]
佬，求个iios.me的签到脚本😂😂。

**Comment by chengkongyiban** [comment]
带佬，把脚本第234行"User-agent"改成"User-Agent"，就能在Loon跑起来了。

**Comment by lowking** [comment]
> 带佬，把脚本第234行"User-agent"改成"User-Agent"，就能在Loon跑起来了。

感谢反馈，已修改
