### ISSUE TITLE
aliYunPanCheckIn支持多帐号吗？

### ISSUE THREAD

**Issue by drw2005** [lowking/Scripts#18]
## 问题脚本
这里填写问题发生的脚本

## 问题描述
这里填写问题描述

## 日志描述
```
这里填写问题脚本输出的日志，否则无法定位问题
```
aliYunPanCheckIn支持多帐号不？请教如何操作？
如果不支持，能否百忙之中支持一下呢？
感谢！

**Comment by lowking** [comment]
不支持，也不打算支持
你可以通过boxjs保存多个会话，再通过切换会话实现多账号
