### ISSUE TITLE
[BUG] 斗鱼鱼吧只能签到第一个，其他签到失败

### ISSUE THREAD

**Issue by fmz200** [lowking/Scripts#21]
## 问题脚本
https://raw.githubusercontent.com/lowking/Scripts/master/douyu/yubaSign.js

## 问题描述
1、斗鱼鱼吧只能签到第一个，其他签到失败，2、代码中await 2秒不生效

## 日志描述
```
日志在图片中
```
![DEF82764-FE14-44DF-812E-F81D7D91D96B_1_102_o](https://user-images.githubusercontent.com/57740735/224519055-cb8267a1-82d4-4f82-a45a-2e4acf598d01.jpeg)

**Comment by lowking** [comment]
脚本维护状态请查看仓库readme，未在使用的不进行维护
