### ISSUE TITLE
[BUG]Loon的配置有点问题

### ISSUE THREAD

**Issue by DavisDing** [lowking/Scripts#24]
## 问题脚本
loon的Script里应该带尖角（ ^ ）
你的脚本为http-request https:\
正确的为http-request ^https
改了之后阿里云盘正常使用了。
另外bilibili这个能用吗？配置好后打开bilibili客户端领了券，但是没提示获取cookie

**Comment by lowking** [comment]
b站大会员领取权益可以用，有效期比较短，一直开着获取cookie就行
