### ISSUE TITLE
[BUG]bingURL任务POST类型传输错误

### ISSUE THREAD

**Issue by geelinsir** [lowking/Scripts#25]
## 问题脚本
bing
## 问题描述
URL任务POST类型传输错误
## 日志描述
URL任务服务器返回“我们这边出现了意外错误。我们将尽快恢复服务 - 请稍后回来查看，以继续享受 Microsoft Rewards。如需帮助，请联系”
## 解决方式
增加 bingPointHeader["content-type"] = 'application/x-www-form-urlencoded; charset=UTF-8'

# bug2

## 问题脚本
sony&douyu（bing没有问题，其他没测）
## 问题描述
"target_boxjs_json_path"相关代码导致报错
## 日志描述
"(node:19716) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '**hasOwnProperty**' of undefined"
## 解决方式
不熟悉boxjs，屏蔽掉了

# bug3

## 问题脚本
sony
## 问题描述
登录报文转义有问题
## 日志描述
账户名或密码出错
## 解决方式
建议直接用文本格式传输json（{"loginID":"xxx","password":"xxx","channel":"WAP"}）

# bug4

## 问题脚本
douyu
## 问题描述
签到吧为空
## 解决方式
86行读取lk.getVal(groupName)之前先判断下有没有，没有先getFollowYuBa()一次，nodejs下首次运行在这遇阻

**Comment by lowking** [comment]
首先感谢反馈。
1,3. 欢迎测试完pr
2. 已增加判断
4. 对于反馈问题前请查看下readme维护列表，不在用的脚本不维护了，有能力的话欢迎pr。
