### ISSUE TITLE
Microsoft Rewards 拼图任务

### ISSUE THREAD

**Issue by geelinsir** [lowking/Scripts#26]
拼图任务的URL是
https://cn.bing.com/spotlight/imagepuzzle?form=ML2BF0&OCID=ML2BF0&PUBL=RewardsDO&PROGRAMNAME=BingDailyOfferIN&CREA=ML2BF0
拼图任务右上角提供了跳过，URL是
https://cn.bing.com/spotlight?q=IzuPeninsulaJapan&spotlightId=IzuPeninsulaJapan&FORM=ml2bf0
也就是说把CREA填入第二个URL的FORM就可以实现完成拼图任务
（上一条Issue的sony我这还有问题，先不close）

**Comment by lowking** [comment]
欢迎pr
sony我这边没问题，没有详细日志无法判断

**Comment by geelinsir** [comment]
研究了一下，这个任务实际上现有脚本就能做，只不过一天得执行两次以上，偶尔会有新任务
