### ISSUE TITLE
朴朴ck获取不了

### ISSUE THREAD

**Issue by gulangyushaonian** [lowking/Scripts#35]
### 您必须确认以下所有内容

- [ ] 我已经阅读了脚本开头的注释。

- [ ] 我确定没有重复的issue。

- [ ] 我确定是脚本的问题，而不是其他原因（例如，```网络```，```操作```等）。

- [ ] 我确定这个问题在最新版本中没有被修复。

### 版本

3.7.3

### 问题描述

朴朴ck获取不了，麻烦看下呢

**Comment by lowking** [comment]
不用朴朴了，优惠力度太低了

**Comment by gulangyushaonian** [comment]
大佬，你现在使用啥呀，哈哈哈

**Comment by gulangyushaonian** [comment]
> 不用朴朴了，优惠力度太低了

大佬，你现在使用啥呀？

**Comment by lowking** [comment]
现在基本不用了，之前有优惠还会去看看

**Comment by gulangyushaonian** [comment]
> 现在基本不用了，之前有优惠还会去看看

好的呢，谢谢大佬！
