### ISSUE TITLE
帐号列表为空，请获取cookie之后再试❌

### ISSUE THREAD

**Issue by xujipm** [lowking/Scripts#8]
帐号列表为空，请获取cookie之后再试❌

提示这个，怎么处理呢，我进QQ会员中心过了，也打开了总成长值

**Comment by lowking** [comment]
获取cookie的rewrite配置了吗，这个提示就字面意思，请仔细查看脚本头部注释的说明哦

**Comment by langzizhui** [comment]
挂了吗，怎么提示api错误

**Comment by lowking** [comment]
> 挂了吗，怎么提示api错误

请重新提交issue，按模版详细填写，解决问题首先要学会如何提问
